### ISSUE TITLE
pspg is not correctly displayed

### ISSUE THREAD

**Issue by okbob** [TragicWarrior/libvterm#26]
I tested run pspg or mc in vshel, and there are some artefacts 

https://github.com/okbob/pspg/issues

vshel
./pspg -f pg_class

**Comment by TragicWarrior** [comment]
@okbob , thanks for the report.  i'm not familiar with the tool.  i tried to invoke it using the flags you gave me, but get this error:

pspg -f pg_class                                                                                               │
│cannot to read file: pg_class

what else do i need to do to run this?

**Comment by okbob** [comment]
I sorry. I wrote it with error.

there should be ./pspg -f pg_class.txt

pspg is pager - or tabular data viewer - so you can start it with cat pg_class.txt | pspg

pg_class.txt is saved postgresql output.

it looks so there are some problem with information about vertical sizes of ncurses windows

![snimek z 2018-12-15 18-19-06](https://user-images.githubusercontent.com/546675/50045608-0cb82580-0096-11e9-8c91-91c36d91119a.png)

**Comment by TragicWarrior** [comment]
@okbob , do you have some sample postgres output that I can use with the tool?  it should be an easy fix as long as i can test it.

**Comment by okbob** [comment]
I have 

[mysql.txt](https://github.com/TragicWarrior/libvterm/files/2687252/mysql.txt)
[ascii.txt](https://github.com/TragicWarrior/libvterm/files/2687255/ascii.txt)

**Comment by TragicWarrior** [comment]
I couldn't reproduce the exact problem you are having
![2018-12-17_12-37](https://user-images.githubusercontent.com/8481559/50107698-fc6c8b80-01f8-11e9-9aeb-55fac4d1eb74.png)

I can see that the Unicode emulation for "full tee" is not working correctly.  I'll fix that and maybe you can retest.  I'll have a fix shortly.

**Comment by TragicWarrior** [comment]
It may or may not be relevant, but my version of pspg is 0.9.3.  what is yours?

**Comment by okbob** [comment]
po 17. 12. 2018 v 19:43 odesílatel TragicWarrior <notifications@github.com>
napsal:

> It may or may not be relevant, but my version of pspg is 0.9.3. what is
> yours?
>
I use 1.6.2, master branch from GIT

I can check another terminal

Pavel

**Comment by okbob** [comment]
po 17. 12. 2018 v 19:45 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> po 17. 12. 2018 v 19:43 odesílatel TragicWarrior <notifications@github.com>
> napsal:
>
>> It may or may not be relevant, but my version of pspg is 0.9.3. what is
>> yours?
>>
> I use 1.6.2, master branch from GIT
>
> I can check another terminal
>

I checked 0.9.3, rxvt, with same result. There can be problem in ncurses -
I use Fedora 28 - so very fresh ncurses libs

**Comment by TragicWarrior** [comment]
I just pushed a fix into master.  Do a fresh pull and take a screenshot.  The rendering should be better... at least partially.

**Comment by okbob** [comment]
po 17. 12. 2018 v 20:21 odesílatel TragicWarrior <notifications@github.com>
napsal:

> I just pushed a fix into master. Do a fresh pull and take a screenshot.
> The rendering should be better... at least partially.
>
maybe some issue on right part. But wrong top part is still. When I run mc
with Czech support - then Czech characters (utf8) are not displayed

I tested this issue on Scientific Linux on very old ncurses 2008 - and I
can see mentioned issue there.

**Comment by okbob** [comment]
po 17. 12. 2018 v 20:32 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> po 17. 12. 2018 v 20:21 odesílatel TragicWarrior <notifications@github.com>
> napsal:
>
>> I just pushed a fix into master. Do a fresh pull and take a screenshot.
>> The rendering should be better... at least partially.
>>
> maybe some issue on right part. But wrong top part is still. When I run mc
> with Czech support - then Czech characters (utf8) are not displayed
>

and some strange - escape I have to press 4 times for leave

**Comment by TragicWarrior** [comment]
@okbob , can you post a screenshot from the new build?

**Comment by okbob** [comment]
![snimek z 2018-12-17 21-01-21](https://user-images.githubusercontent.com/546675/50112215-f7cac600-023e-11e9-9175-f32e8ecc0eda.png)

**Comment by okbob** [comment]
looks like UTF8 related issue - when I force linestyle to ascii - I see some artefacts, that I see a content.

Minimally libvterm doesn't show correctly double lines. When I use just single utr8 lines, then result is much better - under scrolling - when I do some scrolling then crossing lines are broken.

**Comment by TragicWarrior** [comment]
the version of pspg i have installed doesn't appear to support double lines.  can you do the following:

1.  vshell --dump
2.  run your pspg with your double-line mode
3.  immediately exit (both the app and vshell)
4.  send the vterm-xxxxx.dump file

**Comment by okbob** [comment]
[double.txt](https://github.com/TragicWarrior/libvterm/files/2689151/double.txt)

[vterm-3162.dump.txt](https://github.com/TragicWarrior/libvterm/files/2689153/vterm-3162.dump.txt)

**Comment by TragicWarrior** [comment]
@okbob , those files were very helpful.  i have committed some fixes to master.  if you pull and rebuild it should be much improved.  keep in mind that libvterm does not actually support unicode.  It mimics the line drawing utf8 codes by mapping them to ACS similar.  in this case, there is no ACS equivalent for double line drawing characters so it maps to single line.

**Comment by okbob** [comment]
sure. So it is my mistake - I expected so unicode is supported. 

It looks much better, but I still see some artefacts when I do horizontal scrolling. I don't know what is reason - maybe not utf, because I switch PG to use ascii borders. You can use ascii.txt from pspg and some horizontal scrolling
[ascii.txt](https://github.com/TragicWarrior/libvterm/files/2691398/ascii.txt)
![snimek z 2018-12-18 17-36-35](https://user-images.githubusercontent.com/546675/50168352-872db300-02eb-11e9-86a8-fbccee08bba2.png)

**Comment by TragicWarrior** [comment]
Maybe I'm running it differently, but using the file you just provided (which I renamed to ascii2.txt) I invoke the tool from vshell this way:

cat ascii2 |pspg

and it produces this which has no artifact:

[ascii2.txt](https://github.com/TragicWarrior/libvterm/files/2691439/ascii2.txt)

**Comment by okbob** [comment]
try to use right arrow and horizont scroll

**Comment by TragicWarrior** [comment]
still looks fine, what does it do on your system?

![2018-12-18_10-58](https://user-images.githubusercontent.com/8481559/50169806-eec80c00-02b3-11e9-969b-bbe057714576.png)

**Comment by okbob** [comment]
![snimek z 2018-12-18 18-00-31](https://user-images.githubusercontent.com/546675/50169932-f78a0380-02ee-11e9-975d-a3589215861e.png)

I have last version of pspg - there broken bottom bar, and I see missing chars '-' in header lines

**Comment by okbob** [comment]
![snimek z 2018-12-18 18-05-54](https://user-images.githubusercontent.com/546675/50170176-944ca100-02ef-11e9-86ae-0d43732eba9f.png)
after scroll right to end and some press left

**Comment by TragicWarrior** [comment]
are you using a non-english language?

**Comment by okbob** [comment]
út 18. 12. 2018 v 18:15 odesílatel TragicWarrior <notifications@github.com>
napsal:

> are you using a non-english language?
>
yes, my default setting is LANG=cs_CZ.utf8

but I tested LANG=en_US.latin2 without change

**Comment by okbob** [comment]
[vterm-11114.dump.gz](https://github.com/TragicWarrior/libvterm/files/2691565/vterm-11114.dump.gz)

**Comment by okbob** [comment]
út 18. 12. 2018 v 18:27 odesílatel TragicWarrior <notifications@github.com>
napsal:

> what happens if you set
>
> LANG=en_US.UTF-8
>

It is better, the total collapse is out, but missing chars around header
line are still

**Comment by okbob** [comment]
út 18. 12. 2018 v 18:31 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> út 18. 12. 2018 v 18:27 odesílatel TragicWarrior <notifications@github.com>
> napsal:
>
>> what happens if you set
>>
>> LANG=en_US.UTF-8
>>
>
> It is better, the total collapse is out, but missing chars around header
> line are still
>

I tested pspg 0.9.3 with same result.

**Comment by TragicWarrior** [comment]
what happens if you set

```LANGUAGE=en_US```
and
```LANG=en_US.UTF-8```

both before running?

**Comment by okbob** [comment]
út 18. 12. 2018 v 19:06 odesílatel TragicWarrior <notifications@github.com>
napsal:

> what happens if you set
>
> LANGUAGE=en_US
> and
> LANG=en_US.UTF-8
>
> both before running?
>
I don't see any change.

What is your system? I use Fedora 29 on 64bit.

**Comment by TragicWarrior** [comment]
Xubuntu 18.04.1 64-bit

**Comment by TragicWarrior** [comment]
I don't think it will matter much, but I just rewrote the utf8 engine.  Basically it's designed to drop utf8 characters it doesn't recognize and it looks like your environment is passing a few through.  I'm actually getting ready to add true Unicode (utf8 only) support to libvterm using ncursesw which will be a very handsome improvement.  Give the new master branch a try and see what you get.

**Comment by okbob** [comment]
It looks little bit more robust - the bottom bar is not broken too quickly -  but top header lines are broken when I scroll. Is possible so ncurses somewhere raises some utf chars - maybe pspg too. It was not designed to executed without utf.

**Comment by TragicWarrior** [comment]
The plain fact is that the current version of libvterm is not intended to run in a full utf8 mode.  I added support for line-drawing characters to make certain applications render better.  I am starting the process of adding full utf8 support but it's unclear as to how many obstacles I will encounter along the way.  It could take several days or it could take several months.  Fortunately this is a project my employer is interested in so I can devote significant time to it.

**Comment by okbob** [comment]
I tested it - I can see double lines now, but the artefacts when I do horizontal scrolling are there still.

**Comment by TragicWarrior** [comment]
@okbob , what is your LANG env var set to and can you post a screenshot?

**Comment by okbob** [comment]
cs_CZ.UTF-8                 
![snimek z 2018-12-22 18-14-49](https://user-images.githubusercontent.com/546675/50376979-a8f1a780-0615-11e9-8c6c-c16f0d12b0fc.png)

This screenshot is `cat ascii.txt | pspg` and one press right arrow.

**Comment by TragicWarrior** [comment]
@okbob , i cannot reproduce the issue on my system even with LANG set the same as yours.  Can you please run vshell with the --dump flag, cause the problem to manifest, and then immediately exit.

**Comment by okbob** [comment]
[vterm-9550.zip](https://github.com/TragicWarrior/libvterm/files/2705461/vterm-9550.zip)

**Comment by okbob** [comment]
[vterm-14887.dump.gz](https://github.com/TragicWarrior/libvterm/files/2707784/vterm-14887.dump.gz)

Unfortunately I don't see any visible change - the behave and unwanted artefacts are same like prev screenshot

**Comment by okbob** [comment]
Maybe the artefact on bottom bar is less often on some terminals - but the artefacts near header are same

**Comment by TragicWarrior** [comment]
is the ";10H" still showing up in the left column like it was in your most recent screenshot?

**Comment by okbob** [comment]
no, this artefact is fixed - if chars are displayed, then they are valid. Problem is missing chars somewhere.

**Comment by okbob** [comment]
[vterm-18040.dump.gz](https://github.com/TragicWarrior/libvterm/files/2708611/vterm-18040.dump.gz)
![snimek z 2018-12-25 10-55-03](https://user-images.githubusercontent.com/546675/50420318-fba9aa00-0835-11e9-8836-0dd505b368a0.png)
After press "right"

**Comment by TragicWarrior** [comment]
@okbob , i think i see what's happening but because i can't actually reproduce it on my end it's a bit of a guess.  what is the underlying terminal you are running on?  gnome-terminal, linux console, xfce4-terminal, ...?

**Comment by okbob** [comment]
út 25. 12. 2018 v 20:06 odesílatel TragicWarrior <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> , i think i see what's happening but
> because i can't actually reproduce it on my end it's a bit of a guess. what
> is the underlying terminal you are running on? gnome-terminal, linux
> console, xfce4-terminal, ...?
>
I have a gnome-terminal, Fedora Core 29.

Pavel

**Comment by TragicWarrior** [comment]
@okbob , i can reproduce the problem on Fedora 29 which is really helpful.  I'll keep you posted.

BTW, I did not realize you were the author of pspg.  Let me know if you would like it listed on Console Craze which is devoted entirely to console applications.

http://www.console-craze.com

**Comment by TragicWarrior** [comment]
@okbob , i'm 99% sure this issue is now fixed in the branch called 'tab-stop-fix'.  can you pull and test?

**Comment by okbob** [comment]
st 26. 12. 2018 v 19:54 odesílatel TragicWarrior <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> , i'm 99% sure this issue is now fixed
> in the branch called 'tab-stop-fix'. can you pull and test?
>
It is really really significantly better :-)

Still not best - see screenshoot - I just scrolled few times left, right

**Comment by okbob** [comment]
![snimek z 2018-12-26 21-33-30](https://user-images.githubusercontent.com/546675/50456640-4884a200-0956-11e9-8b0a-4e2d8bbe3b9a.png)

**Comment by okbob** [comment]
and looks like horizontal scrolling is much more slower - probably it is not optimized by ncurses and there is full redraw.

**Comment by TragicWarrior** [comment]
@okbob , i found the other culprit.  can you do an additional pull on 'tab-stop-fix' and test?

also, none of the changes i made would have affected horizontal scrolling performance.  ncurses makes some calculated decisions about how to perform the updates.  libvterm simply responds to the control codes emitted by ncurses.

**Comment by TragicWarrior** [comment]
Yes.  The unicode is quite a bit slower.  The box and line drawing characters are 3 bytes each in Unicode and UTF-8, being variable width encoding, takes a few cycles to decode.

**Comment by TragicWarrior** [comment]
@okbob , np!  thanks for the report so I can improve the code.

FWIW, the latest commit in master does improve overall performance a bit.  Also, I noticed that "double" (unicode) preformed extremely well on the native Linux console, xfce4-terminal on Ubuntu 18.04 LTS, and gnome-terminal on Ubuntu 18.04.  I only saw the slowness only in Fedora 29 which suggests some underlying factor (possibly ncursesw version).

**Comment by okbob** [comment]
I tested it in linux console and it is significantly faster, but I checked konsole (KDE terminal) and it is slow. 
Unfortunately, F29 has broken perf, so I cannot do profiling. When I disable colors - and when I use -b option, then it is significantly faster. Maybe there is some relation to color processing.

**Comment by TragicWarrior** [comment]
@okbob , would you mind opening up another issue for color related performance?  i just eliminated an issue related to this in master earlier today, but i've profiled it on Fedora 29 and there's another similar case which doesn't surface on Ubuntu 18.04.

**Comment by okbob** [comment]
sure
